### ISSUE TITLE
NRMS 功能验证报错

### ISSUE THREAD

**Issue by Nirvana-2021** [RUCAIBox/RecBole-TRM#1]
大佬们好，在验证 RecBole 过程中，将 MIND 中的 train、dev 转成 .inter 后，存放在目录 dataset/mind 中，进入 RecBole-TRM toolkit 模块中，运行出现如下错误，大体什么情况，烦请答复，谢谢：

(RecBole) [chwang24@083207 RecBoleTRM]$ python run_recbole_trm.py -m 'NRMS' -d './dataset/mind'
command line args [-m NRMS -d ./dataset/mind] will not be used in RecBole
Traceback (most recent call last):
  File "run_recbole_trm.py", line 16, in <module>
    run_recbole_trm(model=args.model, dataset=args.dataset, config_file_list=config_file_list, model_type=args.model_type)
  File "/data/chwang24/task/RecSys/RecBole/toolkits/RecBoleTRM/recbole_trm/quick_start.py", line 79, in run_recbole_trm
    config = Config(model=model, dataset=dataset, config_file_list=config_file_list, config_dict=config_dict)
  File "/data/chwang24/task/RecSys/RecBole/toolkits/RecBoleTRM/recbole/config/configurator.py", line 75, in __init__
    self.model, self.model_class, self.dataset = self._get_model_and_dataset(model, dataset)
  File "/data/chwang24/task/RecSys/RecBole/toolkits/RecBoleTRM/recbole/config/configurator.py", line 189, in _get_model_and_dataset
    final_model_class = get_model(final_model)
  File "/data/chwang24/task/RecSys/RecBole/toolkits/RecBoleTRM/recbole/utils/utils.py", line 75, in get_model
    raise ValueError('`model_name` [{}] is not the name of an existing model.'.format(model_name))
ValueError: `model_name` [NRMS] is not the name of an existing model.
(RecBole) [chwang24@083207 RecBoleTRM]$

**Comment by 1b33ubble** [comment]
Have you solved it yet? I also encountered this problem while trying to run it today.
